RelativeLayout:
    TabbedPanel:
        do_default_tab: False
        TabbedPanelItem:
            text: "Rgb"
            Image:
                id: rgb
        TabbedPanelItem:
            text: "Disparity"
            Image:
                id: disparity
        TabbedPanelItem:
            text: "Left"
            Image:
                id: left
        TabbedPanelItem:
            text: "Right"
            Image:
                id: right